[params]
  showAuthor = true
  showLastmod = true
  showSummary = true
  showTreeCount = true
  treeRoot = ""
  sidebarSearch = true
  newNum = 10
  relatedNum = 3
  randomNum = 2
  shuffleSeeAlso = true
  showHeaderText = true
  headerText = ""
  maxConcurrency = 16
