[params]
  showAuthor = true
  showLastmod = true
  showSummary = true
  toc = false
  tocAfterSummary = false
  tersePagination = false
  paginationSlots = true
  showTreeCount = true
  treeRoot = ""
  sidebarSearch = true
  newNum = 10
  relatedNum = 3
  randomNum = 2
  shuffleSeeAlso = true
  showHeaderText = true
  maxConcurrency = 16

[module]
  [module.hugoVersion]
  min = "0.134.1"
  extended = false
