[params]
  showAuthor = true
  showLastmod = true
  alwaysIncludeLastmod = false
  showSummary = true
  showThumbnail = true
  showSectionInList = false
  showTagsInList = false
  toc = false
  tocAfterSummary = false
  tersePagination = false
  paginationSlots = true
  recursiveListing = true
  showTreeCount = true
  treeRoot = "/"
  sidebarSearch = true
  sidebarTagThreshold = 0
  newNum = 10
  relatedNum = 3
  randomNum = 2
  randomNumFillTo = false
  shuffleSeeAlso = false
  showHeaderText = true
  maxConcurrency = 16

[markup]
  # Use _merge = "deep" or "shallow" in site level config to import these default values
  [markup.highlight]
    codeFences = true
    lineNumbersInTable = false
    style = "modus-vivendi"

[module]
  [module.hugoVersion]
    min = "0.148.0"
    extended = false
