[params]
  showAuthor = true
  showLastmod = true
  showSummary = true
  toc = false
  tocAfterSummary = false
  tersePagination = false
  paginationSlots = true
  showTreeCount = true
  treeRoot = "/"
  sidebarSearch = true
  sidebarTagThreshold = 0
  newNum = 10
  relatedNum = 3
  randomNum = 2
  shuffleSeeAlso = true
  showHeaderText = true
  maxConcurrency = 16

[module]
  [module.hugoVersion]
    min = "0.134.1"
    max = "0.145.0"
    extended = false
