[params]
  showAuthor = true
  showLastmod = true
  showSummary = true
  toc = false
  tocAfterSummary = false
  showTreeCount = true
  treeRoot = ""
  sidebarSearch = true
  newNum = 10
  relatedNum = 3
  randomNum = 2
  shuffleSeeAlso = true
  showHeaderText = true
  maxConcurrency = 16
