name = "curegit"
homepage = "https://github.com/curegit/nagoya"
demosite = "https://curegit.github.io/nagoya-example/"
license = "MIT"
licenselink = "https://github.com/curegit/nagoya/blob/master/LICENSE"
min_version = "0.125.0"

[author]
  name = "curegit"
  homepage = "https://curegit.jp/"
