name = "Nagoya"
license = "MIT"
licenselink = "https://github.com/curegit/nagoya/blob/master/LICENSE"
homepage = "https://github.com/curegit/nagoya"
demosite = "https://curegit.github.io/nagoya-example/"

[author]
  name = "curegit"
  homepage = "https://curegit.jp/"
